name: Breakify CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.1' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit
      run: vendor/bin/phpunit --testdox

    - name: Run PHP_CodeSniffer (PSR-12)
      run: vendor/bin/phpcs --standard=PSR12 src/
